export const restList = [
  {
    id: '150602',
    name: 'Raimens Cafe 79',
    cloudinaryImageId: 'eohdm5sdnq6e2u46xeux',
    locality: 'Palace Guttahalli',
    areaName: 'Seshadripuram',
    costForTwo: '₹300 for two',
    cuisines: ['Bakery', 'Pizzas'],
    avgRating: 4.3,
    avgRatingString: '4.3',
    totalRatingsString: '5K+',
    sla: {
      deliveryTime: 29,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '25-30 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '132818513',
          name: 'Indiana Pasta',
          category: 'Pizza & Pasta',
          imageId: '6f23d65b8d1b79065526cd81cdf621de',
          inStock: 1,
          isVeg: 1,
          price: 20000,
        },
      },
      {
        info: {
          id: '55845014',
          name: 'Honey Chilli Potato',
          category: 'Chinese',
          imageId: 'd7e71eb3337399aff625e98d6639c890',
          inStock: 1,
          isVeg: 1,
          price: 16000,
        },
      },
      {
        "info": {
            "id": "36499024",
            "name": "Nutella Shake",
            "category": "Beverages",
            "imageId": "729e0e92af6a0d4290911e600bd963f4",
            "inStock": 1,
            "isVeg": 1,
            "price": 16000,}
      }
    ],
  },

  {
    id: '380756',
    name: 'Gama Gama Hotel',
    cloudinaryImageId: 'jxn3gonh9ulhv0fwlzjx',
    locality: 'NR Colony',
    areaName: 'Basavanagudi',
    costForTwo: '₹150 for two',
    cuisines: ['Street Food', 'South Indian'],
    avgRating: 4.3,
    veg: true,
    parentId: '329256',
    avgRatingString: '4.3',
    totalRatingsString: '500+',

    sla: {
      deliveryTime: 32,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '224083',
    name: 'New Bhimas Garden Veg',
    cloudinaryImageId: 'zbhim5nglia5pgekdjxe',
    locality: 'Sampangiram Nagar',
    areaName: 'Seshadripuram',
    costForTwo: '₹200 for two',
    cuisines: ['Chinese', 'Chaat'],
    avgRating: 3.7,
    veg: true,
    parentId: '145973',
    avgRatingString: '3.7',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 32,
      lastMileTravel: 4.9,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '4.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '253546',
    name: 'Biryani Paradise',
    cloudinaryImageId: 'xb4uew4pkvs0jzbnybks',
    locality: 'Koramangala',
    areaName: 'Adugodi',
    costForTwo: '₹300 for two',
    cuisines: ['Biryani', 'Arabian'],
    avgRating: 3.6,
    parentId: '137',
    avgRatingString: '3.6',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 30,
      lastMileTravel: 4.9,
      serviceability: 'SERVICEABLE',
      slaString: '25-30 mins',
      lastMileTravelString: '4.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '606918',
    name: 'Chickpet Donne Biryani House',
    cloudinaryImageId: 'orlqk94usnkgjq7zoun8',
    locality: '3rd Block',
    areaName: 'Jayanagar',
    costForTwo: '₹250 for two',
    cuisines: ['Biryani', 'Kebabs'],
    avgRating: 4.1,
    parentId: '5634',
    avgRatingString: '4.1',
    totalRatingsString: '500+',
    sla: {
      deliveryTime: 35,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '499250',
    name: 'Iyengars Inn',
    cloudinaryImageId: 'zndhb5gcoqo2zffza8fh',
    locality: 'Sunkenahalli',
    areaName: 'Basavanagudi',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian', 'Snacks'],
    avgRating: 4.4,
    veg: true,
    parentId: '299137',
    avgRatingString: '4.4',
    totalRatingsString: '20+',
    sla: {
      deliveryTime: 35,
      lastMileTravel: 4.8,
      serviceability: 'SERVICEABLE',
      slaString: '35-40 mins',
      lastMileTravelString: '4.8 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '596794',
    name: 'Dharmik Veg',
    cloudinaryImageId: 'ov7sttp8k3rjqd2kzj73',
    locality: 'Pulakeshinagar',
    areaName: 'Central Bangalore',
    costForTwo: '₹300 for two',
    cuisines: ['South Indian', 'Chinese'],
    avgRating: 4.1,
    veg: true,
    parentId: '356853',
    avgRatingString: '4.1',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 34,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '491572',
    name: 'Kaapi Katte',
    cloudinaryImageId: 'rmssgdcxzzkkjb9aussv',
    locality: 'Gubbi Veeranna Road',
    areaName: 'Malleshwaram',
    costForTwo: '₹200 for two',
    cuisines: ['South Indian', 'Combo'],
    avgRating: 4.2,
    veg: true,
    parentId: '113011',
    avgRatingString: '4.2',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 31,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '142299',
    name: 'The Green Path',
    cloudinaryImageId: 'f9iz9xlggq1uyysbyefe',
    locality: 'Sampige Road',
    areaName: 'Malleshwaram',
    costForTwo: '₹310 for two',
    cuisines: ['Beverages'],
    avgRating: 4,
    veg: true,
    parentId: '209198',
    avgRatingString: '4.0',
    totalRatingsString: '50+',
    sla: {
      deliveryTime: 44,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '40-45 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '648545',
    name: 'Aramane Donne Biriyani',
    cloudinaryImageId: '91437abf416a589b29eb7920424ae05c',
    locality: 'Margosa Rd',
    areaName: 'Malleshwaram',
    costForTwo: '₹399 for two',
    cuisines: ['Biryani', 'Indian'],
    avgRating: 4,
    parentId: '7133',
    avgRatingString: '4.0',
    totalRatingsString: '20+',
    sla: {
      deliveryTime: 32,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '580194',
    name: 'Sakkath Dosa',
    cloudinaryImageId: 'bwwdz3viu7lblm6yb53c',
    locality: 'Gandhi Bazaar',
    areaName: 'Basavanagudi',
    costForTwo: '₹150 for two',
    cuisines: ['South Indian'],
    avgRating: 4.2,
    veg: true,
    parentId: '347279',
    avgRatingString: '4.2',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 33,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '807103',
    name: 'Madurai Meenakshi Bhavan',
    cloudinaryImageId: '2a85523e385211c01775af18403284df',
    locality: 'Gandhi Nagar',
    areaName: 'Madurai Meenakshi Bhavan',
    costForTwo: '₹300 for two',
    cuisines: ['Indian', 'Chinese'],
    parentId: '249877',
    avgRatingString: 'NEW',
    sla: {
      deliveryTime: 36,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '35-40 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '554053',
    name: 'Amman Parotta Plaza',
    cloudinaryImageId: 'acfqzod86qbnhgztxsyg',
    locality: 'Srirampuram',
    areaName: 'Rajajinagar',
    costForTwo: '₹300 for two',
    cuisines: ['South Indian'],
    avgRating: 3.8,
    parentId: '333270',
    avgRatingString: '3.8',
    totalRatingsString: '100+',
    sla: {
      deliveryTime: 36,
      lastMileTravel: 5,
      serviceability: 'SERVICEABLE',
      slaString: '35-40 mins',
      lastMileTravelString: '5.0 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '31765',
    name: 'Donne Biriyani Angadi Mane',
    cloudinaryImageId: 'b4b19cfe9911a0e0327d5a9f2ac7490f',
    locality: 'Bashyam Circle',
    areaName: 'Malleshwaram',
    costForTwo: '₹300 for two',
    cuisines: ['Biryani', 'South Indian'],
    avgRating: 4,
    parentId: '2915',
    avgRatingString: '4.0',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 35,
      lastMileTravel: 5.5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.5 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '176071',
    name: "Brahmins' Thatte Idli",
    cloudinaryImageId: 'pe1savupw5miak1g0ylt',
    locality: 'Vyalikaval',
    areaName: 'Malleshwaram',
    costForTwo: '₹150 for two',
    cuisines: ['South Indian'],
    avgRating: 4.5,
    veg: true,
    parentId: '1312',
    avgRatingString: '4.5',
    totalRatingsString: '5K+',
    sla: {
      deliveryTime: 34,
      lastMileTravel: 5.7,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.7 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '3241',
    name: 'Meghana Foods',
    cloudinaryImageId: 'e0vvulfbahjxjz6k4uwi',
    locality: 'Residency Road',
    areaName: 'Residency Road',
    costForTwo: '₹500 for two',
    cuisines: ['Biryani', 'Andhra'],
    avgRating: 4.6,
    parentId: '635',
    avgRatingString: '4.6',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 18,
      lastMileTravel: 2.1,
      serviceability: 'SERVICEABLE',
      slaString: '15-20 mins',
      lastMileTravelString: '2.1 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '132818513',
          name: 'Indiana Pasta',
          category: 'Pizza & Pasta',
          imageId: '6f23d65b8d1b79065526cd81cdf621de',
          inStock: 1,
          isVeg: 1,
          price: 20000,
        },
      },
    ],
  },
  {
    id: '3369',
    name: 'Truffles',
    cloudinaryImageId: 'cd832b6167eb9f88aeb1ccdebf38d942',
    locality: 'St. Marks Road',
    areaName: 'St. Marks Road',
    costForTwo: '₹450 for two',
    cuisines: ['American', 'Desserts'],
    avgRating: 4.6,
    parentId: '218065',
    avgRatingString: '4.6',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 23,
      lastMileTravel: 0.9,
      serviceability: 'SERVICEABLE',
      slaString: '20-25 mins',
      lastMileTravelString: '0.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '30034',
    name: "Mani's Dum Biryani",
    cloudinaryImageId: 'y0fjz8h4ad8nfzkmbznu',
    locality: 'Haudin Road',
    areaName: 'Ulsoor',
    costForTwo: '₹499 for two',
    cuisines: ['Andhra', 'Biryani'],
    avgRating: 4.5,
    parentId: '623',
    avgRatingString: '4.5',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 29,
      lastMileTravel: 3.6,
      serviceability: 'SERVICEABLE',
      slaString: '25-30 mins',
      lastMileTravelString: '3.6 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '464509',
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cloudinaryImageId: 'b2edbc28b7b8219d6e0a9c049ce06658',
    locality: 'Pulkeshi Nagar',
    areaName: 'Frazer Town',
    costForTwo: '₹300 for two',
    cuisines: ['American', 'Snacks'],
    avgRating: 4.4,
    parentId: '371281',
    avgRatingString: '4.4',
    totalRatingsString: '5K+',
    sla: {
      deliveryTime: 32,
      lastMileTravel: 4.2,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '4.2 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '30531',
    name: 'Hotel Empire',
    cloudinaryImageId: 'qltgnkyywuo5gmnpqzbm',
    locality: 'Brigade Road',
    areaName: 'Church Street',
    costForTwo: '₹450 for two',
    cuisines: ['North Indian'],
    avgRating: 4.4,
    parentId: '475',
    avgRatingString: '4.4',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 31,
      lastMileTravel: 2.3,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '2.3 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },

  {
    id: '31766',
    name: 'Donne Biriyani Angadi Mane',
    cloudinaryImageId: 'b4b19cfe9911a0e0327d5a9f2ac7490f',
    locality: 'Bashyam Circle',
    areaName: 'Malleshwaram',
    costForTwo: '₹300 for two',
    cuisines: ['Biryani', 'South Indian'],
    avgRating: 4,
    parentId: '2915',
    avgRatingString: '4.0',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 35,
      lastMileTravel: 5.5,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.5 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '176073',
    name: "Brahmins' Thatte Idli",
    cloudinaryImageId: 'pe1savupw5miak1g0ylt',
    locality: 'Vyalikaval',
    areaName: 'Malleshwaram',
    costForTwo: '₹150 for two',
    cuisines: ['South Indian'],
    avgRating: 4.5,
    veg: true,
    parentId: '1312',
    avgRatingString: '4.5',
    totalRatingsString: '5K+',
    sla: {
      deliveryTime: 34,
      lastMileTravel: 5.7,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '5.7 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '3243',
    name: 'Meghana Foods',
    cloudinaryImageId: 'e0vvulfbahjxjz6k4uwi',
    locality: 'Residency Road',
    areaName: 'Residency Road',
    costForTwo: '₹500 for two',
    cuisines: ['Biryani', 'Andhra'],
    avgRating: 4.6,
    parentId: '635',
    avgRatingString: '4.6',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 18,
      lastMileTravel: 2.1,
      serviceability: 'SERVICEABLE',
      slaString: '15-20 mins',
      lastMileTravelString: '2.1 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '33690',
    name: 'Truffles',
    cloudinaryImageId: 'cd832b6167eb9f88aeb1ccdebf38d942',
    locality: 'St. Marks Road',
    areaName: 'St. Marks Road',
    costForTwo: '₹450 for two',
    cuisines: ['American', 'Desserts'],
    avgRating: 4.6,
    parentId: '218065',
    avgRatingString: '4.6',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 23,
      lastMileTravel: 0.9,
      serviceability: 'SERVICEABLE',
      slaString: '20-25 mins',
      lastMileTravelString: '0.9 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '30035',
    name: "Mani's Dum Biryani",
    cloudinaryImageId: 'y0fjz8h4ad8nfzkmbznu',
    locality: 'Haudin Road',
    areaName: 'Ulsoor',
    costForTwo: '₹499 for two',
    cuisines: ['Andhra', 'Biryani'],
    avgRating: 4.5,
    parentId: '623',
    avgRatingString: '4.5',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 29,
      lastMileTravel: 3.6,
      serviceability: 'SERVICEABLE',
      slaString: '25-30 mins',
      lastMileTravelString: '3.6 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '464508',
    name: "Leon's - Burgers & Wings (Leon Grill)",
    cloudinaryImageId: 'b2edbc28b7b8219d6e0a9c049ce06658',
    locality: 'Pulkeshi Nagar',
    areaName: 'Frazer Town',
    costForTwo: '₹300 for two',
    cuisines: ['American', 'Snacks'],
    avgRating: 4.4,
    parentId: '371281',
    avgRatingString: '4.4',
    totalRatingsString: '5K+',
    sla: {
      deliveryTime: 32,
      lastMileTravel: 4.2,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '4.2 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
  {
    id: '30532',
    name: 'Hotel Empire',
    cloudinaryImageId: 'qltgnkyywuo5gmnpqzbm',
    locality: 'Brigade Road',
    areaName: 'Church Street',
    costForTwo: '₹450 for two',
    cuisines: ['North Indian'],
    avgRating: 4.4,
    parentId: '475',
    avgRatingString: '4.4',
    totalRatingsString: '10K+',
    sla: {
      deliveryTime: 31,
      lastMileTravel: 2.3,
      serviceability: 'SERVICEABLE',
      slaString: '30-35 mins',
      lastMileTravelString: '2.3 km',
      iconType: 'ICON_TYPE_EMPTY',
    },
    menu: [
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
      {
        info: {
          id: '47383765',
          name: 'Chicken Korma',
          category: 'Main Course (North Indian)',
          description:
            'North-India style rich Mughlai korma of chicken braised in ghee, spices and nuts.',
          imageId: 'qb41u5gjb19ikjnanlec',
          inStock: 1,
          price: 25900,
        },
      },
    ],
  },
];
